version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    networks:
      - car_booking_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - car_booking_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - car_booking_network

networks:
  car_booking_network:
    driver: bridge

