version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - car_booking_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - car_booking_network

networks:
  car_booking_network:
    driver: bridge
